### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by SCIENTIST2004** [Glampi42/ONI-Mods#13]
Game just randomly crashed idk why exactly the only thiong i know is its something with the mod 

NullReferenceException

KBatchedAnimController.SetLayer (System.Int32 layer) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
KAnimControllerBase.SetLayer (System.Int32 layer) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
KBatchedAnimController.SetLayer (System.Int32 layer) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
ChainErrand.ChainOverlay.AddToVisible (KMonoBehaviour errandRef, System.Collections.Generic.HashSet`1[T] collectedErrands) (at <309f3e89e64e4625a75933e28acd8448>:0)
ChainErrand.ChainOverlay.Update () (at <309f3e89e64e4625a75933e28acd8448>:0)
OverlayScreen.LateUpdate () (at <93e6d51e7c504f4483a782aaaf7248c3>:0)

Build: U52-623711-SCD

[Player.log](https://github.com/user-attachments/files/16576160/Player.log)

**Comment by Glampi42** [comment]
This should be fixed in v1.0.7.0. Please try to open the chain tool on the same world you did when the crash happened. If it still occurs, please open a new issue (with the crash message and Player.log).
