### ISSUE TITLE
[ChainErrand] Constructions with Dig Errands

### ISSUE THREAD

**Issue by nullvoid8** [Glampi42/ONI-Mods#14]
Build: U52-626616-SC
Mod version: 1.1.0.0

What I did:
Replaced a stairway (zigzagging two block high ledges) with a ladder, with the climbing spots marked as Step 2

What I expected:
The ladders marked as Step 2 would be dug out last, ensuring traversability throughout the build process

What happened:
Dig errands were completed early, while the build itself was completed last as designated

---

I presume this means that the dig orders generated by the ghost are not being governed by the Chain.

Here is an example I constructed while writing this issue:

Ladders # 1 and # 2 have been dug out, while # 3 is over an undug Ice tile.

![image](https://github.com/user-attachments/assets/24a0cf49-7967-4fbe-bfee-3adb57ac34ef)
![image](https://github.com/user-attachments/assets/95238fd5-ec2d-4364-b3e2-cec8e914d91f)
![image](https://github.com/user-attachments/assets/588a751f-084f-4063-99ce-6074918dad71)

**Comment by Glampi42** [comment]
This was an oversight. Fixed in v1.1.1.0: now the dig errands are added to the same chain link their corresponding construct errands are in. Thanks for the report.
