### ISSUE TITLE
[MOD TRANSLATION]: SPANISH Translation for "Advanced Flow Management"

### ISSUE THREAD

**Issue by edubistkrank** [Glampi42/ONI-Mods#15]
SPANISH Translation for "Advanced Flow Management"

.- edubistkrank -.

[AdvancedFlowManagement_es.zip](https://github.com/user-attachments/files/17056594/AdvancedFlowManagement_es.zip)

**Comment by Glampi42** [comment]
Added in v2.0.6.0, thank you for your help!
