### ISSUE TITLE
Crash on digging

### ISSUE THREAD

**Issue by 1000i100** [Glampi42/ONI-Mods#2]
[Utopia Young.sav.zip](https://github.com/Glampi42/ONI-Mods/files/12777947/Utopia.Young.sav.zip)

To reproduce the bug, load the game on linux, ideally with the same mod loaded, and add a digging task. When your start selecting an area to dig, no problem, but when you release your mouse click, the game freeze, then crash.

For now, i fixed it by removing the mod.

**Comment by Glampi42** [comment]
I was able to find the cause of the crash, the v1.1.7 should fix it. Close the issue if you can make a dig errand without your game crashing.

**Comment by 1000i100** [comment]
Yep, it work fine now :)
