### ISSUE TITLE
Compatibility with mod "Customize Buildings (more capacity, less dupes)"

### ISSUE THREAD

**Issue by Arkia-456** [Glampi42/ONI-Mods#4]
Hi !

I think I have a compatibility issue with the mod "Customize Buildings (more capacity, less dupes)". This mod increases storage capacity of several buildings like Liquid reservoirs.
By default with this mod, liquid reservoir's storage capacity is 99000kg. I set them to 5000kg, but with the flow management, they continue to store liquid.

The configuration of liquid reservoir :
![image](https://github.com/Glampi42/ONI-Mods/assets/145221230/5e4bcc0e-49ee-4e7a-bdc4-d022124c47ab)

And the flow : 
![image](https://github.com/Glampi42/ONI-Mods/assets/145221230/808e80fd-864a-404b-aa31-0fa4ea03560e)

Note that I changed reservoir capacity before being full. I saved game and reloaded it in hope to "update" flow management, but it continues to fill reservoir.

I'm not sure if the problem is on your side or other's mod side. Here is the link to the other mod : https://steamcommunity.com/sharedfiles/filedetails/?id=1818138009

**Comment by aurwei** [comment]
Sorry, it was an option in the other mod I didn't see.

**Comment by Glampi42** [comment]
Well, then problem solved;)
