### ISSUE TITLE
Translation request zh_cn

### ISSUE THREAD

**Issue by friends-xiaohuli** [Glampi42/ONI-Mods#6]
A very powerful module, but I didn't understand the language file. Please

**Comment by Glampi42** [comment]
Hi, I would be glad to provide a chinese translation, but I don't know this language. What I could do is to translate the text using ChatGPT - here is an attempt of that. Please review this translation. Every chinese text is a translation of the english text that is located right above.
[zh_cn.txt](https://github.com/Glampi42/ONI-Mods/files/14850722/zh_cn.txt)

**Comment by friends-xiaohuli** [comment]
> Hi, I would be glad to provide a chinese translation, but I don't know this language. What I could do is to translate the text using ChatGPT - here is an attempt of that. Please review this translation. Every chinese text is a translation of the english text that is located right above. [zh_cn.txt](https://github.com/Glampi42/ONI-Mods/files/14850722/zh_cn.txt)

I'm sorry, this is a multi project warehouse. I haven't used "AdvancedFlowManagement" yet. If you need help with proofreading, I can provide text correction after use. "HighlightOverlay" is currently my goal, thank you for your help. I have understood the language file, and I may try to pull one later. Thank you again for your reply!

**Comment by Glampi42** [comment]
Thank you for your contribution for translating this mod!
