### ISSUE TITLE
BUG！

### ISSUE THREAD

**Issue by Bei-Ning** [Glampi42/ONI-Mods#9]
NullReferenceException: Object reference not set to an instance of an object

HighlightOverlay.Patches.Overlay_Patches+ConfigureDiagram_Patch.Postfix (OverlayLegend+OverlayInfo overlayInfo, System.Boolean isRefresh, OverlayLegend __instance) (at <6bcb2addf6be43cd890f58b28a51b5da>:0)
(wrapper dynamic-method) OverlayLegend.OverlayLegend.PopulateOverlayInfoUnits_Patch1(OverlayLegend,OverlayLegend/OverlayInfo,bool)
OverlayLegend.PopulateGeneratedLegend (OverlayLegend+OverlayInfo info, System.Boolean isRefresh) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
OverlayLegend.SetLegend (OverlayLegend+OverlayInfo overlayInfo) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
OverlayLegend.SetLegend (OverlayModes+Mode mode, System.Boolean refreshing) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
OverlayScreen.ActivateLegend () (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
OverlayScreen.ToggleOverlay (HashedString newMode, System.Boolean allowSound) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
OverlayMenu.OnToggleSelect (KIconToggleMenu+ToggleInfo toggle_info) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
KIconToggleMenu.OnClick (System.Int32 i) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
KIconToggleMenu+<>c__DisplayClass18_0.<RefreshButtons>b__0 () (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
Util.Signal (System.Action action) (at <0a61a0e7beaf44b6b425814476821935>:0)
KToggle.Click () (at <0a61a0e7beaf44b6b425814476821935>:0)
KToggle.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <0a61a0e7beaf44b6b425814476821935>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e9635660f69b4d9d84c085aeda3be353>:0)
UnityEngine.EventSystems.EventSystem:Update()

Build: U52-623711-SD
![image](https://github.com/user-attachments/assets/86f71583-25ee-401f-adc9-eebd20f7a795)

**Comment by Glampi42** [comment]
Which mod version do you have installed? It should be v1.0.4.0. If it is a previous version, consider using the ModUpdater.

**Comment by Glampi42** [comment]
An outdated version of the mod was used.
